# Generated by Django 4.2.5 on 2023-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('a', models.CharField(max_length=250)),
                ('b', models.CharField(max_length=250)),
                ('c', models.CharField(max_length=250)),
            ],
        ),
    ]
